#!/bin/sh
curl -L 2>/dev/null https://chee.party/$1 \
    | hxclean \
    | hxselect -c '#content article:nth-child(2) .entry-header, #content article:nth-child(2) .entry-content' \
    | html2text-cpp -ascii -links -nobs -width 72
