#!/bin/sh
deno compile --allow-net --allow-run fingerd.ts
sudo mv fingerd /bin/partyfingerd
sudo cp partyfingerd.service /etc/systemd/system/
sudo systemctl enable --now partyfingerd
echo ready for fingering
